# Generated by Django 5.0.3 on 2024-03-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('number', models.IntegerField(verbose_name='Номер машины')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер места')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.car', verbose_name='Автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Номер места',
            },
        ),
    ]
